import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {mkdtemp,rm,readFile} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {executeInFreshContext} from '../worker/execution.js';import {VerificationSessions} from '../worker/verification-sessions.js';import {ReceiptStore} from '../worker/receipts.js';
const destination='https://job-boards.greenhouse.io/fixture/jobs/123';
const challenge="<h2>Email verification</h2><p>Security code sent to your email address</p><form id=\"verify\"><label>Security code<input maxlength=\"8\" aria-label=\"security code\"></label><button>Submit application</button></form>";
const html=`<form id="application"><label>Full name<input name="name" required></label><label>Email<input name="email" type="email" required></label><button>Submit application</button></form><script>window.initial=0;window.verifications=0;document.querySelector('#application').onsubmit=e=>{e.preventDefault();window.initial++;document.body.innerHTML=${JSON.stringify(challenge)};document.querySelector('#verify').onsubmit=e=>{e.preventDefault();window.verifications++;document.body.innerHTML='<h2>Your application was successfully submitted.</h2>'}}</script>`;
for(const mutation of ['none','destination','closed','retained-form','changed-contact','ambiguous-code'])test('real execution retains verification-only browser: '+mutation,async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'otp-execution-'));const real=await chromium.launch({headless:true});let page,context;const browser={newContext:async options=>{context=await real.newContext(options);const original=context.newPage.bind(context);context.newPage=async()=>{page=await original();await page.route('https://job-boards.greenhouse.io/**',route=>route.fulfill({contentType:'text/html',body:mutation==='retained-form'||mutation==='changed-contact'||mutation==='ambiguous-code'?html.replace(JSON.stringify(challenge),JSON.stringify(challenge.replace('<label>Security code','<label>Full name<input name="preservedName" value="Ada Lovelace"></label><label>Email<input name="preservedEmail" value="ada@example.test"></label><label>Security code')+(mutation==='ambiguous-code'?'<label>Security code<input maxlength="8" aria-label="security code"></label>':''))):html}));return page};return context}};t.after(async()=>{await real.close();await rm(dir,{recursive:true,force:true})});const registry=new VerificationSessions({closeOnSuccess:true});const receipts=new ReceiptStore(path.join(dir,'receipts'));const payload={profile:{id:'synthetic',contact:{firstName:'Ada',lastName:'Lovelace',email:'ada@example.test'},applicationAnswers:{}},opportunity:{id:'role',applyUrl:destination,applicationDestinationVerified:true},application:{id:'synthetic-attempt',standingPolicyVersion:1,answers:{},claim:{attemptId:'attempt-one'}}};const persist=receipts.verificationRecorder(payload);let commits=0;
 const result=await receipts.run(payload,markFinalActionStarted=>executeInFreshContext({browser,payload,artifactsDirectory:dir,urlPolicy:{assertAllowed(){},async assertPublic(){},assertNetworkSafe(){}},verificationSessions:registry,markFinalActionStarted,authorizeFinal:async()=>({decision:'permit',permit:'synthetic-permit'}),commitFinal:async()=>{commits++;return{allowed:true}}}));
 assert.equal(commits,1,JSON.stringify(result));assert.equal(result.status,'needs_human');const metadata=result.requirements[0].verificationSession;if(mutation==='ambiguous-code'){assert.equal(metadata,undefined);assert.equal(page.isClosed(),true);await registry.closeAll();return;}assert.ok(metadata,JSON.stringify(result));assert.equal(page.isClosed(),false);assert.equal(await page.evaluate(()=>window.initial),1);assert.equal(JSON.stringify(result).includes('verificationContinuation'),false);assert.equal((await receipts.status(payload.application.id)).status,'final_action_started');
 if(mutation==='changed-contact')await page.locator('[name=preservedName]').fill('Changed');if(mutation==='destination')await page.goto('https://job-boards.greenhouse.io/fixture/jobs/other');if(mutation==='closed')await context.close();let persisted=0;const code='TEST1234';const verified=await registry.verify({...metadata,sessionId:metadata.id,code},{authorize:async()=>({allowed:true}),persistReceipt:async receipt=>{persisted++;assert.equal(await page.evaluate(()=>window.verifications),1);await persist({...receipt,receipt:{...receipt.receipt,simulated:true}})}});
 if(mutation==='none'||mutation==='retained-form'){assert.equal(verified.status,'submitted');assert.equal(persisted,1);assert.equal(page.isClosed(),true);assert.equal((await receipts.status(payload.application.id)).status,'submitted');const disk=await readFile(path.join(dir,'receipts',payload.application.id+'.json'),'utf8');assert.equal(disk.includes(code),false);assert.equal((await receipts.run(payload,async()=>{throw Error('must never replay')})).status,'needs_human');}else{assert.equal(verified.status,'needs_human');assert.equal(persisted,0)}await registry.closeAll();
});
