import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { JsonStore } from '../src/store.js';
import { SqliteStore } from '../src/sqlite-store.js';
import { ApplicationService } from '../src/service.js';
import { createHttpServer } from '../src/http.js';
import { ownerSubmissionSentAt } from '../dashboard/owner-submission.mjs';
const identity={profileId:'applicant',actorId:'chat'};
const body=()=>({recordKey:'chat/confirmation-one',company:'Example',title:'Engineer',jobUrl:null,submissionDate:'2026-10-06',observedAt:'2026-10-06T10:00:00Z',evidence:{source:'owner_provided_linkedin',successText:'Application status\nApplication submitted\nnow',reference:'Owner chat confirmation',sha256:'a'.repeat(64)},historicalAnswers:[{question:'Experience years',answer:'3'}]});
async function fixture(t,kind){const dir=await mkdtemp(path.join(os.tmpdir(),'external-sends-'));const store=await (kind==='sqlite'?new SqliteStore(path.join(dir,'state.sqlite')):new JsonStore(path.join(dir,'state.json'))).init();let writes=0;const service=new ApplicationService({store,config:{defaultMode:'full_time',modes:{full_time:{dailyApplicationCap:100}},execution:{maxApplicationsPerDay:100}},profiles:{patch(){writes++;}}});t.after(async()=>{store.close?.();await rm(dir,{recursive:true,force:true});});return {service,store,profileWrites:()=>writes};}
for(const kind of ['json','sqlite']){
 test(`${kind}: owner confirmation without URL is durable, idempotent and does not run forms or promote answers`,async t=>{const f=await fixture(t,kind);const input=body();const r=await f.service.externalSubmissions.record(input,identity);const repeat=await f.service.externalSubmissions.record(input,identity);assert.equal(repeat.applicationId,r.applicationId);assert.equal(repeat.duplicate,true);const s=f.store.snapshot();assert.equal(s.applications.length,1);assert.equal(s.attempts.length,0);assert.equal(s.applications[0].receipt,undefined);assert.equal(s.applications[0].executionMode,'external_owner');assert.equal(s.applications[0].answers.Experience,undefined);assert.equal(s.applications[0].ownerSubmission.historicalAnswers[0].reusable,false);assert.equal(f.profileWrites(),0);assert.equal(f.service.chromeQueue.list(identity.profileId).pending,0);assert.equal(ownerSubmissionSentAt(s.applications[0],new Date('2026-10-06T11:00:00Z')),'2026-10-06T12:00:00.000Z');await assert.rejects(f.service.externalSubmissions.record({...input,title:'Different'},identity),e=>e.status===409);});
 test(`${kind}: profile isolation and strong URL dedup preserve original receipt`,async t=>{const f=await fixture(t,kind);await f.store.mutate(s=>{s.opportunities.push({id:'job',profileId:'applicant',company:'Example',title:'Engineer',applyUrl:'https://jobs.ashbyhq.com/example/11111111-1111-4111-8111-111111111111/application'});s.applications.push({id:'old',profileId:'applicant',opportunityId:'job',status:'submitted',receipt:{submittedAt:'2026-09-30T10:00:00Z'},createdAt:'2026-09-30T10:00:00Z'});});const input={...body(),jobUrl:'https://jobs.ashbyhq.com/example/11111111-1111-4111-8111-111111111111?utm_source=linkedin'};assert.equal((await f.service.externalSubmissions.record(input,identity)).applicationId,'old');assert.equal(f.store.snapshot().applications[0].receipt.submittedAt,'2026-09-30T10:00:00Z');assert.equal(f.store.snapshot().attempts.length,0);const other=await f.service.externalSubmissions.record(input,{profileId:'other',actorId:'other'});assert.notEqual(other.applicationId,'old');await assert.rejects(f.service.externalSubmissions.record({...body(),profileId:'other'},identity),e=>e.status===400);});
 test(`${kind}: same title without URL is held for identity check; distinct URLs do not collapse`,async t=>{const f=await fixture(t,kind);await f.service.externalSubmissions.record({...body(),jobUrl:'https://jobs.example/one'},identity);const pending=await f.service.externalSubmissions.record({...body(),recordKey:'no-url'},identity);assert.equal(pending.identityMatchPending,true);const distinct=await f.service.externalSubmissions.record({...body(),recordKey:'two',jobUrl:'https://jobs.example/two'},identity);assert.equal(distinct.duplicate,false);assert.equal(f.store.snapshot().applications.length,2);});
}
test('reject non-confirmations, future/invalid dates and credential fields without state changes',async t=>{const f=await fixture(t,'sqlite');for(const patch of [{evidence:{...body().evidence,successText:'Clicked apply'}},{observedAt:'bad'},{submissionDate:'2026-02-30'},{submissionDate:'2099-01-01'},{jobUrl:'http://employer.example/job'},{jobUrl:'https://127.0.0.1/job'},{historicalAnswers:[{question:'Password',answer:'must not save'}]}])await assert.rejects(f.service.externalSubmissions.record({...body(),...patch},identity));assert.equal(f.store.snapshot().applications.length,0);});
test('HTTP endpoint binds authenticated applicant and cannot advance an owner-held queue',async t=>{const f=await fixture(t,'sqlite');const q=await f.service.chromeQueue.add({url:'https://employer.example/blocked'},identity);await f.service.chromeQueue.claim({sessionId:'chat'},identity);await f.service.chromeQueue.checkpoint(q.application.id,{sessionId:'chat',kind:'account',message:'Sign in',checkpoint:{}},identity);const server=createHttpServer({service:f.service,authenticate:r=>r.headers.authorization==='Bearer fixture'?identity:null});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const url=`http://127.0.0.1:${server.address().port}/v1/external-submissions`;assert.equal((await fetch(url,{method:'POST',body:JSON.stringify(body())})).status,401);const r=await fetch(url,{method:'POST',headers:{authorization:'Bearer fixture','content-type':'application/json'},body:JSON.stringify(body())});assert.equal(r.status,200);assert.equal(f.service.chromeQueue.list(identity.profileId).current.status,'waiting_owner');});
test('collector rejects incomplete proof and retains date-only Sofia semantics at observation midnight',()=>{const application={ownerSubmission:{version:1,channel:'linkedin',submissionActor:'owner_linkedin',identityMatchPending:false,...body(),historicalAnswers:undefined}};const n=new Date('2026-10-06T10:30:00Z');assert.ok(ownerSubmissionSentAt(application,n));assert.equal(ownerSubmissionSentAt({...application,ownerSubmission:{...application.ownerSubmission,identityMatchPending:true}},n),null);assert.equal(ownerSubmissionSentAt({...application,ownerSubmission:{...application.ownerSubmission,evidence:{...application.ownerSubmission.evidence,successText:'Review your application'}}},n),null);});
import { patchOwnerSubmissionCollector } from '../dashboard/collector-patch.js';
test('collector patch is idempotent and fails closed on unexpected source',()=>{const source=" function verifiedSentAt() {\n if(receiptDate)return receiptDate;\n }\n const effectiveStatus=a=>displayStatus(sentDates.get(a.id)&&a.status==='skipped'? 'done':a.status);";const result=patchOwnerSubmissionCollector(source);assert.equal(patchOwnerSubmissionCollector(result),result);assert.match(result,/ownerSubmissionSentAt\(application,now\)/);assert.throws(()=>patchOwnerSubmissionCollector('unrelated source'));});
import { inactivityDeadline } from '../src/application-lifecycle.js';
test('external history participates in existing inactivity lifecycle without manufacturing a receipt',async t=>{const f=await fixture(t,'sqlite');await f.service.externalSubmissions.record(body(),identity);const a=f.store.snapshot().applications[0];assert.equal(inactivityDeadline(a),'2026-10-27T12:00:00.000Z');assert.equal((await f.service.reconcileInactivity('2026-10-28T12:00:00Z')).closed,1);assert.equal(f.store.snapshot().applications[0].receipt,undefined);});
test('later URL enriches a no-link record; exact known receipt merges without double counting',async t=>{const f=await fixture(t,'sqlite');const r=await f.service.externalSubmissions.record(body(),identity);const linked={...body(),jobUrl:'https://employer.example/one'};assert.equal((await f.service.externalSubmissions.record(linked,identity)).applicationId,r.applicationId);assert.equal(f.store.snapshot().applications.length,1);assert.equal(f.store.snapshot().opportunities[0].applyUrl,linked.jobUrl);const second={...body(),recordKey:'separate',company:'Other company',title:'Other role'};const a=await f.service.externalSubmissions.record(second,identity);await f.store.mutate(s=>{s.opportunities.push({id:'known-job',profileId:'applicant',company:'Other company',title:'Other role',applyUrl:'https://employer.example/known'});s.applications.push({id:'known-app',profileId:'applicant',opportunityId:'known-job',status:'submitted',receipt:{submittedAt:'2026-09-30T10:00:00Z'}});});const matched=await f.service.externalSubmissions.record({...second,jobUrl:'https://employer.example/known'},identity);assert.equal(matched.applicationId,'known-app');const old=f.store.snapshot().applications.find(x=>x.id===a.applicationId);assert.equal(old.ownerSubmission,undefined);assert.equal(old.status,'external_duplicate');assert.equal((await f.service.externalSubmissions.record({...second,jobUrl:'https://employer.example/known'},identity)).applicationId,'known-app');});

test('collector counts owner browser receipts once while rejecting incomplete browser proof',()=>{
 const observedAt=new Date().toISOString();
 const proof={version:1,channel:'browser',submissionActor:'owner_browser',identityMatchPending:false,recordKey:'fixture/browser',
  submissionDate:new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Sofia',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(observedAt)),observedAt,
  jobUrl:'https://job-boards.greenhouse.io/example/jobs/123',finalUrl:'https://job-boards.greenhouse.io/example/jobs/123/confirmation',
  evidence:{source:'owner_provided_employer_confirmation',reference:'Owner exact-role confirmation',sha256:'a'.repeat(64),successText:'Your application has been received.'}};
 assert.ok(ownerSubmissionSentAt({ownerSubmission:proof}));
 for(const changed of [{finalUrl:'https://unrelated.example/confirmation'},{jobUrl:null},{submissionActor:'agent'},{evidence:{...proof.evidence,successText:'Review your application'}}])
  assert.equal(ownerSubmissionSentAt({ownerSubmission:{...proof,...changed}}),null);
});
