import assert from 'node:assert/strict';
import test from 'node:test';import{mkdtemp,writeFile,rm}from'node:fs/promises';import path from'node:path';import os from'node:os';
import{chromium}from'playwright';import{automateApplication}from'../worker/automation.js';
import{ApplicationService}from'../src/service.js';import{ProfileStore}from'../src/profile-store.js';import{JsonStore}from'../src/store.js';import{DiscoveryService}from'../src/discovery/service.js';import{createHttpServer}from'../src/http.js';import{NeedsInputError,NeedsReviewError}from'../src/adapters/errors.js';
const agent={actorId:'synthetic-reviewer',profileId:'synthetic',roles:['agent']};
const destination='https://job-boards.greenhouse.io/fixture/jobs/123';
// Synthetic official GH transport hosts the observed Teamtailor-style upload
// controller. This tests normal discovery/API/worker semantics, not live egress.
const html=(url,changedQuestion=false)=>`<form onsubmit="event.preventDefault();window.submits++;document.body.innerHTML='<h2>Your application was successfully submitted.</h2>'"><label>Email<input type="email" name="email" required></label><label>${changedQuestion?'Describe a different question':'Why this role?'}<textarea name="motivation" required></textarea></label><div id="upload_resume_field" data-controller="forms--inputs--upload"><label>Upload CV<input id="candidate_resume_remote_url" type="file" required></label><div id="previews"></div></div><label>Additional files<input id="candidate_file_remote_url" type="file"></label><button>Submit Application</button></form><script>window.submits=0;window.uploads=0;document.querySelector('input[type=file]').onchange=e=>{window.uploads++;setTimeout(()=>{document.querySelector('#previews').innerHTML=${JSON.stringify(`<div data-controller="forms--inputs--upload-preview" data-forms--inputs--upload-preview-url-value="${url}"><div data-forms--inputs--upload-preview-target="name"><a data-forms--inputs--upload-preview-target="link">resume.pdf</a></div><input hidden type="text" name="candidate[resume_remote_url]" data-forms--inputs--upload-preview-target="urlInput" value="${url}"></div>`)};const replacement=e.target.cloneNode();replacement.value='';replacement.required=false;e.target.replaceWith(replacement);},50);};</script>`;
async function fixture(t){
 const dir=await mkdtemp(path.join(os.tmpdir(),'reviewed-teamtailor-'));const resume=path.join(dir,'resume.pdf');await writeFile(resume,'%PDF-1.4 synthetic owner-authorized document');const browser=await chromium.launch({headless:true});const profiles=await new ProfileStore(path.join(dir,'profiles.json'),{allowMissing:true}).init();
 await profiles.patch('synthetic',{contact:{firstName:'Ada',lastName:'Lovelace',email:'ada@example.test',phone:'+10000000000',location:'Remote'},documents:{resume},applicationAnswers:{motivation:'I build reliable TypeScript services.'},skills:['TypeScript']});
 await profiles.setStandingSubmissionPolicy('synthetic',{mode:'automatic',modes:['full_time'],sources:['greenhouse'],destinationHosts:['job-boards.greenhouse.io'],answerClasses:['profile_fact','grounded_prose','link','resume'],dailyCap:5,campaignCap:5},{...agent,roles:['owner']});
 const store=await new JsonStore(path.join(dir,'state.json')).init();const config={defaultMode:'full_time',execution:{maxApplicationsPerDay:10,workerCallbackToken:'synthetic-worker-token'},discovery:{sourceOptions:{greenhouse:{boards:[{token:'fixture',company:'Fixture Employer'}]}}},modes:{full_time:{minimumScore:0,autoApply:false,dailyApplicationCap:8,requireConfirmationFor:[]}}};
 let base,contexts=0,commits=0,finals=0,changedQuestion=false;const urls=[],fingerprints=[],errors=[];
 async function request(route,body,token='synthetic-agent-token'){const r=await fetch(base+route,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,value:await r.json()};}
 const adapter={name:'synthetic-real-browser',async submit(payload){contexts++;const url='https://storage.example.test/upload-'+contexts+'-resume.pdf';urls.push(url);const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('https://job-boards.greenhouse.io/**',r=>r.fulfill({contentType:'text/html',body:html(url,changedQuestion)}));try{const result=await automateApplication({page,...payload,artifactsDirectory:dir,authorizeFinal:async input=>{fingerprints.push(input.previewFingerprint);const r=await request('/v1/internal/final-decision',input,'synthetic-worker-token');assert.equal(r.status,200);return r.value;},commitFinal:async input=>{const r=await request('/v1/internal/final-commit',input,'synthetic-worker-token');assert.equal(r.status,200);commits++;return r.value;},markFinalActionStarted:async()=>{finals++;}});if(result.status==='submitted')return{...result.receipt,simulated:true};if(result.status==='needs_input')throw new NeedsInputError(result.message,result.requirements,result);throw new NeedsReviewError(result.message,result.requirements,result);}finally{await context.close();}}};
 const service=new ApplicationService({store,profiles,config,adapter});service.enqueue=()=>{};const description='TypeScript engineering. Fully remote worldwide.';const row={id:123,title:'TypeScript Engineer',absolute_url:destination,content:description,location:{name:'Remote worldwide'},offices:[{name:'Remote worldwide'}],departments:[]};const discovery=new DiscoveryService({applicationService:service,profiles,config,fetchImpl:async()=>new Response(JSON.stringify(row))});const server=createHttpServer({service,discovery,profiles,config,authenticate:req=>req.headers.authorization==='Bearer synthetic-agent-token'?agent:null});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));await browser.close();await rm(dir,{recursive:true,force:true});});
 const considered=await request('/v1/discovery/consider',{candidate:{title:row.title,company:'Fixture Employer',source:'greenhouse',description,applyUrl:destination,location:'Remote worldwide',remote:true},fit:{decision:'relevant',reason:'Synthetic complete current role requires verified TypeScript and worldwide remote.'},apply:false});assert.equal(considered.status,200);assert.equal(considered.value.status,'ready',JSON.stringify(considered.value));const applied=await request('/v1/opportunities/'+considered.value.opportunityId+'/apply',{answers:{motivation:'I build reliable TypeScript services.'}});assert.equal(applied.status,202);const app=applied.value;
 return{service,profiles,store,request,app,resume,urls,fingerprints,errors,setQuestion:()=>{changedQuestion=true;},counts:()=>({contexts,commits,finals}),pending:()=>service.list('confirmations','synthetic').find(i=>i.status==='pending')};
}
for(const mutation of ['none','content','profile','question','destination'])test('two-context authenticated exact CV review: '+mutation,async t=>{
 const f=await fixture(t);await f.service.execute(f.app.id);const hold=f.pending();assert.equal(hold.kind,'final_policy_hold',JSON.stringify(hold));assert.equal(f.counts().finals,0);assert.ok(hold.preview.filled.some(field=>field.type==='file'&&field.uploadAcknowledged===true&&field.files?.[0]?.size>0));const review={approved:true,review:{previewFingerprint:hold.previewFingerprint,authorizationSource:'synthetic standing delegated exact-field review',fields:hold.preview.filled.filter(v=>v.source==='application answer').map(v=>({step:v.step,key:v.key,sourceKind:'saved_profile_fact',sourceReference:'synthetic saved current motivation',profileAnswerKey:'motivation'}))}};const approved=await f.request('/v1/confirmations/'+hold.id,review);assert.equal(approved.status,200,JSON.stringify(approved.value));
 if(mutation==='content')await writeFile(f.resume,'%PDF-1.4 changed document content');if(mutation==='profile')await f.profiles.patch('synthetic',{applicationAnswers:{motivation:'Changed owner fact.'}});if(mutation==='question')f.setQuestion();if(mutation==='destination')await f.store.mutate(s=>{s.opportunities.find(o=>o.id===f.app.opportunityId).applyUrl='https://job-boards.greenhouse.io/fixture/jobs/124';});
 await f.service.execute(f.app.id);const saved=f.service.list('applications','synthetic').find(a=>a.id===f.app.id);assert.equal(f.counts().contexts,2);assert.notEqual(f.urls[0],f.urls[1]);assert.deepEqual(f.errors,[]);
 if(mutation==='none'){assert.equal(saved.status,'submitted',JSON.stringify(saved));assert.equal(saved.receipt.simulated,true);assert.deepEqual(f.counts(),{contexts:2,commits:1,finals:1});assert.equal(f.fingerprints[0],f.fingerprints[1]);}else{assert.notEqual(saved.status,'submitted');assert.equal(f.counts().commits,0);assert.equal(f.counts().finals,0);}
});
